sudo: false

language: node_js
node_js:
    - "4.2.4"
before_install:
    - npm install -g npm
    - npm --version

cache:
  directories:
    - node_modules

script:
  - npm run build


deploy:
  provider: releases
  api_key: "fd0663dda3c262d0d511c213761897597267c406"
  file: "README.md"
  skip_cleanup: true
  on:
    tags: true