sudo: false

language: node_js
node_js:
    - "4.2.4"
before_install:
    - npm install -g npm
    - npm --version

cache:
  directories:
    - node_modules

script:
  - npm run build


deploy:
  provider: releases
  api_key: "0b9a0d0a38c749e7d64ba4713c76bd9be30f7891"
  file: "README.md"
  skip_cleanup: true
  on:
    tags: true