sudo: false

language: node_js
node_js:
    - "4.2.4"
before_install:
    - npm install -g npm
    - npm --version

cache:
  directories:
    - node_modules

script:
  - npm run build
  - gem install travis
  - travis setup releases


deploy:
  provider: releases 
  file: "README.md"
  skip_cleanup: true
  on:
    tags: true